name: reference
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"  # Update ke versi null safety jika perlu

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3  # Pastikan versi terbaru
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.4.4  # Tambahkan untuk WebView

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cat.jpg
    - assets/web/index.html  # Tambahkan HTML sebagai aset

  
  
