workflows:
  flutter_build:
    name: Flutter Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      java: 11  # Pastikan menggunakan JDK 11 agar kompatibel dengan Gradle 7.5.1
    scripts:
      - name: Check Java Version
        script: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version

      - name: Set JAVA_HOME (JDK 11)
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 11)
          echo "Using JAVA_HOME: $JAVA_HOME"

      - name: Debug Build Path
        script: |
          echo "Current directory: $(pwd)"
          ls -la
          cd flutter_AppCoffe
          echo "Inside flutter_AppCoffe:"
          ls -la  # Mengecek apakah pubspec.yaml ada

      - name: Run Flutter Doctor
        script: |
          cd flutter_AppCoffe
          flutter doctor -v

      - name: Clean Build
        script: |
          cd flutter_AppCoffe
          flutter clean

      - name: Get Flutter Dependencies
        script: |
          cd flutter_AppCoffe
          flutter pub get

      - name: Run Gradle Manually (Debugging)
        script: |
          cd flutter_AppCoffe/android
          ./gradlew assembleRelease --stacktrace

      - name: Build APK
        script: |
          cd flutter_AppCoffe
          flutter build apk --release --verbose

    artifacts:
      - flutter_AppCoffe/build/app/outputs/flutter-apk/*.apk
