workflows:
  flutter_build:
    name: Flutter Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      java: 11
    scripts:
      - name: Check Java Version
        script: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version

      - name: Set JAVA_HOME (JDK 11)
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 11)
          echo "Using JAVA_HOME: $JAVA_HOME"
          java -version

      - name: Debug Build Path
        script: |
          echo "Current directory: $(pwd)"
          ls -la
          cd flutter_AppCoffe
          echo "Inside flutter_AppCoffe:"
          ls -la  # Cek apakah pubspec.yaml ada

      - name: Run Flutter Doctor
        script: |
          cd flutter_AppCoffe
          flutter doctor -v

      - name: Debug Android Folder
        script: |
          cd flutter_AppCoffe
          echo "Checking android directory..."
          ls -la android/
          echo "Checking gradle/wrapper file..."
          ls -la android/gradle/wrapper

      - name: Generate Gradle Wrapper (Jika Perlu)
        script: |
          cd flutter_AppCoffe/android
          flutter pub get
          flutter build apk --config-only

      - name: Fix Gradle Permissions
        script: |
          cd flutter_AppCoffe/android
          chmod +x gradlew

      - name: Clean Build
        script: |
          cd flutter_AppCoffe
          flutter clean

      - name: Get Flutter Dependencies
        script: |
          cd flutter_AppCoffe
          flutter pub get

      - name: Run Gradle Manually (Debugging)
        script: |
          cd flutter_AppCoffe/android
          ./gradlew assembleRelease --stacktrace

      - name: Build APK
        script: |
          cd flutter_AppCoffe
          flutter build apk --release --verbose

    artifacts:
      - flutter_AppCoffe/build/app/outputs/flutter-apk/*.apk
