workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.myapp" # Ganti dengan package name aplikasi kamu
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
